import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Contracts",
  description: "Generated by contracts",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Bonheur+Royale&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="light bg-white">{children}</div>
      </body>
    </html>
  );
}
